version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chronospace-network

  backend:
    image: chronospace-be:latest
    container_name: backend
    build:
      context: ../chronospace-be
      dockerfile: Dockerfile
    environment:
      DB_SOURCE: postgresql://postgres:password@database:5432/chronospace
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - chronospace-network

  frontend:
    image: chronospace-fe:latest
    container_name: frontend
    build:
      context: ../chronospace-fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - chronospace-network

volumes:
  postgres_data:

networks:
  chronospace-network: