import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Chonospace | Book it now.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return ;
}
