version: '3.8'

services:
  chronospace-be:
    image: chronospace-be:latest
    build:
      context: ../chronospace-be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  chronospace-fe:
    image: chronospace-fe:latest
    build:
      context: ../chronospace-fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - chronospace-be

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chronospace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: